version: '3.8'

services:
  db-42:
    image: postgres:latest
    restart: always
    env_file:
      - .db.env
    networks:
      - my-network
    ports:
      - 5432:5432

  db:
    image: postgres:latest
    restart: always
    env_file:
      - .db.env
    networks:
      - my-network
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data

  # REMOVE THIS BEFORE SUBMITING THE PROJECT
  # run only for unit testing
  db-test:
    image: postgres:latest
    restart: always
    env_file:
      - .db.env
    networks:
      - my-network
    ports:
      - 5432:5432

networks:
  my-network:
    driver: bridge
