name: Hello World

on:
  push:
    branches:
      - hello
    # Calling the job only if we push on hello branch

jobs:
  hello_world_job:
    runs-on: ubuntu-22.04
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"
