name: Deployment pipeline

on:
  push:
    branches:
      - master

jobs:
  frontend_deployment:
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.20.0'
      - name: Install dependencies
        run: npm install
      - name: Run unitest
        run: npm run test
